---

- name: cleanup | cleanup fragments from installation
  block:
    - name: cleanup | remove aur_builder user
      ansible.builtin.user:
        name: aur_builder
        state: absent
        remove: yes
  tags:
    - setup

