---

- name: install | pacman packages
  block:
    - name: install | pacman packages | coding
      community.general.pacman:
        name:
          - git
          # - code
          # - nodejs
        state: latest
      register: packages
      until: packages is success
      retries: 10
      delay: 10
    - name: install | pacman packages | essential
      community.general.pacman:
        name:
          - firefox
          # - insync
          # - thunderbird
          # - telegram
          # - obsidian
        state: latest
      register: packages
      until: packages is success
      retries: 10
      delay: 10
    - name: install | pacman packages | additional 
      community.general.pacman:
        name:
          - steam
          - 
        state: latest
      register: packages
      until: packages is success
      retries: 10
      delay: 10
  rescue:
    - set_fact: task_failed=true
