---

- name: packages | add oh-my-zsh
  block:
    - name: oh-my-zsh | install zsh
      community.general.pacman:
        name:
          - zsh
        state: latest
      register: oh_my_zsh

    - name: oh-my-zsh | download oh-my-zsh script
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/oh_my_zsh_script.sh
        mode: 0755
      when: oh_my_zsh.changed
      register: oh_my_zsh_download

    - name: oh-my-zsh | install oh-my-zsh script
      become_user: '{{ user_login }}'
      shell: sh -c /tmp/oh_my_zsh_script.sh
      when: oh_my_zsh_download.changed
      register: oh_my_zsh_install
      ignore_errors: True

    # jonathan 
    # sorin
    # strug

    # headline

    - name: oh-my-zsh | copy .zshrc
        copy:
          src: files/.zshrc
          dest: /home/{{ user_login }}/.zshrc
          owner: '{{ user_login }}'
          group: '{{ user_login }}'
          mode: 0644

    - name: users | {{ user_login }} | create dircolor directory
      tags: user_config
      file:
        path: /home/{{ user_login }}/{{ item.dir }}
        state: directory
        owner: '{{ user_login }}'
        group: '{{ user_login }}'
        mode: 0755
      with_items:
        - { dir: .dir_colors }

    - name: oh-my-zsh | copy dircolors
      copy:
        src: files/dircolors
        dest: /home/{{ user_login }}/.dir_colors/dircolors
        owner: '{{ user_login }}'
        group: '{{ user_login }}'
        mode: 0644

    - name: oh-my-zsh | remove oh-my-zsh script
      file:
        path: /tmp/oh_my_zsh_script.sh
        state: absent